//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFANDEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attintance
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<double> Bounce { get; set; }
        public Nullable<double> penalty { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<double> Total { get; set; }
    
        public virtual User User { get; set; }
    }
}
