//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFANDEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int Id { get; set; }
        public Nullable<int> EmpId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<double> Loan { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public string Desc { get; set; }
        public string Type { get; set; }
        public Nullable<int> State { get; set; }
    
        public virtual User User { get; set; }
    }
}
